version: '3.2'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DB}'
    healthcheck:
        test: ["CMD", "pg_isready", "-d", "${PG_DB}", "-U", "${PG_USER}"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
    - "${PG_PORT}:5432"
    volumes:
    -  'postgres:/var/lib/postgresql/data'
    networks:
    - mainnet

  server:
    container_name: server
    depends_on:
      postgres:
        condition: service_healthy
    links: 
        - postgres
    build:
      context: .
      dockerfile: ./backend/cmd/server/Dockerfile
    environment:
      ALBUM_SERVICE_HOST: 0.0.0.0
      ALBUM_SERVICE_PORT: 8090
      PG_CONNECTION_STRING: "postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}?sslmode=${PG_SSL}"
    networks:
    - mainnet

volumes:
  postgres:

networks:
  mainnet:
    driver: bridge
